config/routes.rb
University::Application.routes.draw do
  resources :registers do
    member do
      get :delete_data
    end
  end

  resources :registrations

  resources :subjects

  resources :semesters do
    member do
      get :get_drop_down_options
    end
  end

  root to: 'registers#index'

  

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_and_belongs_to_many :subject
  has_many :register
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "emu", password: "123"
  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end


  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render action: 'show', status: :created, location: @semester }
      else
        format.html { render action: 'new' }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url }
      format.json { head :no_content }
    end
  end

  def get_drop_down_options

    val = params[:id]
    subject = Subject.find_all_by_semester_no(val)
    #Use val to find records
    @subject_options = subject.collect{|x| "#{x.subject_name}"}
    id_card = params[:user_id]
    @previous_subjects = []
    register = Register.find_all_by_semester_no(val)
    @register = register
    @register.each do |element|
      if element.student_id_card == id_card
        @subject_options.delete(element.subject_name)
        @previous_subjects.push(element.subject_name)
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:semester_no)
    end
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/_form.html.erb
<%= form_for(@semester) do |f| %>
  <% if @semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% @semester.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :semester_no %><br>
    <%= f.number_field :semester_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing semester</h1>

<%= render 'form' %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/get_drop_down_options.js.erb
<%= render :partial=>"shared/drop_down_options" %>

app/views/semesters/index.html.erb
<h1>Listing semesters</h1>

<table>
  <thead>
    <tr>
      <th>Semester no</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.semester_no %></td>
        <td><%= link_to 'Show', semester %></td>
        <td><%= link_to 'Edit', edit_semester_path(semester) %></td>
        <td><%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semester', new_semester_path %>

app/views/semesters/new.html.erb
<h1>New semester</h1>

<%= render 'form' %>

<%= link_to 'Back', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester no:</strong>
  <%= @semester.semester_no %>
</p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>