config/routes.rb
University::Application.routes.draw do
  resources :registers do
    member do
      get :delete_data
    end
  end

  resources :registrations

  resources :subjects

  resources :semesters do
    member do
      get :get_drop_down_options
    end
  end

  root to: 'registers#index'

  

end

app/models/register.rb
class Register < ActiveRecord::Base
  SEMESTER_TYPES = ["1","2","3","4","5","6","7","8"]
  validates :student_id_card, presence: true
  validates_uniqueness_of :semester_no, :scope => [:student_id_card, :subject_name], :message => "/ subject name already taken"
  belongs_to :semester
  has_many :subjects
  accepts_nested_attributes_for :subjects
  #validates_uniqueness_of :subject_name, :scope => [:student_id_card, :semester_no], :message => "Already Taken"

  before_save :eligibility_test

  private
  def eligibility_test
    @register = Register.all
    @register.each do |i|
      if i.subject_name == subject_name
        if i.semester_no != semester_no
          if i.student_id_card == student_id_card
            errors[:base] << "subject already taken to semester #{i.semester_no}"
            return false
          end
        end
      end
    end
  end

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
    @subject_options = []
  end

  # GET /registers/1/edit
  def edit
    @register = Register.find(params[:id])

    subject = Subject.find_all_by_semester_no(@register.semester_no)
    @subject_options = subject.collect { |x| "#{x.subject_name}" }
    @previous_subjects = []
    @registration = Register.all
    @registration.each do |element|
      if element.student_id_card == @register.student_id_card
        if element.semester_no == @register.semester_no
          @subject_options.delete(element.subject_name)
          @previous_subjects.push(element.subject_name)
        end
      end
    end

  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)
    #@register = Register.find(params[:id])
    subject = Subject.find_all_by_semester_no(@register.semester_no)          #find subjects from SUBJECT table based on semester_no
    #Use val to find records
    @previous_subjects = []                                                   #subjects that are already taken to this semester
    @subject_options = subject.collect { |x| "#{x.subject_name}" }            #subjects available to take in this semester
    @registration = Register.all
    @registration.each do |element|                                           #listing the available & editable subjects
      if element.student_id_card == @register.student_id_card
        if element.semester_no == @register.semester_no
          @subject_options.delete(element.subject_name)
          @previous_subjects.push(element.subject_name)
        end
      end
    end

    previous_subjects = @previous_subjects

    # finding the subjects belongs to the unique ID card holder student & for a specific semester
    student_id_no = @register.student_id_card
    semester_no = @register.semester_no
    subject_nam = @register.subject_name

    unless (subject_nam.blank?)                            # check which subjects to add/destroy in/from the DB
      subjects_to_add = subject_nam - previous_subjects
      subjects_to_destroy = previous_subjects - subject_nam
    else
      subjects_to_destroy = previous_subjects
      subjects_to_add = nil
    end

    # adding the subjects
    err = false
    unless subjects_to_add.blank?
      temp_subject = []
      subjects_to_add.each do |subject|
        @register = Register.new({semester_no: semester_no, student_id_card: student_id_no, subject_name: subject})
        if @register.save
          temp_subject.push (subject)
        else err = true
        end
      end
      temp_subject.each do |subject|
        @subject_options.delete(subject)
        @previous_subjects.push(subject)
      end
    end

    # deleting the subjects
    unless subjects_to_destroy.blank?
      temp_subject = []
      subjects_to_destroy.each do |subject|
        Register.destroy_all(:student_id_card => student_id_no, :semester_no => semester_no, :subject_name => subject)
        temp_subject.push(subject);
      end
      temp_subject.each do |subject|
        @previous_subjects.delete(subject)
        @subject_options.push(subject)
      end
    end

    respond_to do |format|
      if !err
        if subject_nam.blank?
          format.html { redirect_to action: 'index', notice: 'Register was successfully updated.' }
        else
          format.html { redirect_to action: 'index', notice: 'Register was successfully updated.' }
        end

        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update

    @register = Register.find(params[:id])

    subject = Subject.find_all_by_semester_no(@register.semester_no)
    #Use val to find records
    @previous_subjects = []
    @subject_options = subject.collect { |x| "#{x.subject_name}" }
    @registration = Register.all
    @registration.each do |element|
      if element.student_id_card == @register.student_id_card
        if element.semester_no == @register.semester_no
          @subject_options.delete(element.subject_name)
          @previous_subjects.push(element.subject_name)
        end
      end
    end

    previous_subjects = @previous_subjects

    # finding the subjects belongs to the unique ID card holder student & for a specific semester
    student_id_no = @register.student_id_card
    semester_no = params[:register][:semester_no]
    subject_nam = params[:register][:subject_name]

    unless (subject_nam.blank?)
      subjects_to_add = subject_nam - previous_subjects
      subjects_to_destroy = previous_subjects - subject_nam
    else
      subjects_to_destroy = previous_subjects
      subjects_to_add = nil
    end

    # adding the subjects
    err = false
    unless subjects_to_add.blank?
      temp_subjects = []
      subjects_to_add.each do |subject|
          @register = Register.new({semester_no: semester_no, student_id_card: student_id_no, subject_name: subject})
          if @register.save
            temp_subjects.push (subject)
          else err = true
          end
      end
      temp_subjects.each do |subject|
        @subject_options.delete(subject)
        @previous_subjects.push(subject)
      end
    end

    # deleting the subjects
    unless subjects_to_destroy.blank?
      temp_subjects = []
      subjects_to_destroy.each do |subject|
        Register.destroy_all(:student_id_card => student_id_no, :semester_no => semester_no, :subject_name => subject)
        temp_subjects.push(subject);
      end
      temp_subjects.each do |subject|
        @previous_subjects.delete(subject)
        @subject_options.push(subject)
      end
    end

      respond_to do |format|
        if !err
          if subject_nam.blank?
            format.html { redirect_to action: 'index', notice: 'Register was successfully updated.' }
          else
            format.html { redirect_to action: 'index', notice: 'Register was successfully updated.' }
          end

          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @register.errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to @register }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common
  # setup or constraints between actions.
  def set_register
    @register = Register.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def register_params
    params.require(:register).permit(:semester_no, {:subject_name => []}, :student_id_card)
  end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
    <% if @register.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

          <ul>
            <% @register.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :student_id_card %>
      <br>
      <%= f.text_field :student_id_card %>
    </div>

    <div class="field">
      <%= f.label :semester_no %>
      <br>
      <%= f.select :semester_no, Register::SEMESTER_TYPES,
                   prompt: 'Select a Semester' %>
    </div>

    <div class="field">
      <div class="dynamic_subject">
      </div>
    </div>



    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $("#register_semester_no").change(function () {
            user_id = $("#register_student_id_card").val();
            //console.log(user_id);
            var url = '/semesters/' + $(this).val() + '/get_drop_down_options?user_id='+user_id;
            //$("#subject_name").removeOption(/./)
            $.get(url, function (data) {
                //$('#subject_name').addOption(data, false);
                //            console.log(data);
            });
        });
    });

    /*
    $(document).on('click',"#register_subject_name_", function(){
        user_id = $("#register_student_id_card").val();
        semestr_id = $("#register_semester_no").val();
        flag = false
        if($(this).prop('checked')){
            flag = true;
            //var url = '/semesters/' + $(this).attr('name') + '/get_drop_down_options?user_id & semestr_id & flag ='+user_id + semestr_id + flag;
            //console.log('Add: '+$(this).attr('name'));
        }
        else{
            var url = '/semesters/' + $(this).attr('name') + '/get_drop_down_options?user_id & semestr_id & flag='+user_id + semestr_id + flag;
            $.get(url, function (data) {
                //            console.log(data);
            });
            //console.log('Delete: '+$(this).attr('name'));
        }
    });  */

    <%= render :partial=>"shared/drop_down_options" %>
</script>

app/views/registers/edit.html.erb
<h1>Editing register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <thead>
    <tr>
      <th>Student id card</th>
      <th>Semester no</th>
      <th>Subject name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.student_id_card %></td>
        <td><%= register.semester_no %></td>
        <td><%= register.subject_name %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester no:</strong>
  <%= @register.semester_no %>
</p>

<p>
  <strong>Subject name:</strong>
  <%= @register.subject_name %>
</p>

<p>
  <strong>Student id card:</strong>
  <%= @register.student_id_card %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>