config/routes.rb
University::Application.routes.draw do
  resources :registers do
    member do
      get :delete_data
    end
  end

  resources :registrations

  resources :subjects

  resources :semesters do
    member do
      get :get_drop_down_options
    end
  end

  root to: 'registers#index'

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :semester
  accepts_nested_attributes_for :semester
  belongs_to :register

  validates_uniqueness_of :subject_name, :scope => :semester_no
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "emu", password: "123"
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end




  # POST /subjects
  # POST /subjects.json
  def create
  @subject = Subject.new(subject_params)

  subject_nam = params[:subject][:subject_name]
  semester_no = params[:subject][:semester_no]

  #semester_nos = params[:subject][:subject_name]

    err = false
    unless semester_nos.blank?
    semester_no.each do |semester|
      @subjects = Subject.new({semester_no: semester, subject_name: subject_nam})
      unless @subjects.save
        err = true
      end
    end
      else err = true
    end


    respond_to do |format|

      if !err
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update

    @subject = Subject.find(params[:id])
    semester_no = params[:subject][:semester_no]
    subject_name = @subject.subject_name

    err = false
    semester_no.each do |semester|
      unless Subject.exists?({semester_no: semester, subject_name: subject_name})
        @subject = Subject.new({semester_no: semester, subject_name: subject_name})
        unless @subject.save
          err = true
        end
      end
    end

    respond_to do |format|
      if !err
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject_name,{:semester_no => []})
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_name %><br>
    <%= f.text_field :subject_name %>
  </div>
  <div class="field">
    <%= f.label :semester_no %><br>
    <% Semester.count.times do |i| %>
        <%= label_tag i+1 %>:
        <%= check_box_tag "subject[semester_no][]", i+1 %> <br />
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <thead>
    <tr>
      <th>Subject name</th>
      <th>Semester no</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subject_name %></td>
        <td><%= subject.semester_no %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject name:</strong>
  <%= @subject.subject_name %>
</p>

<p>
  <strong>Semester no:</strong>
  <%= @subject.semester_no %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>